# settings.py - Configuration settings for the STM32 ADXL345 Space Shooter game

# =========================
# SERIAL SETTINGS
# =========================

SERIAL_PORT = "COM5"
BAUD_RATE = 115200


# =========================
# SCREEN SETTINGS
# =========================

WIDTH = 900
HEIGHT = 600
FPS = 60


# =========================
# PLAYER SETTINGS
# =========================

PLAYER_WIDTH = 64
PLAYER_HEIGHT = 64

MAX_LIVES = 4
INVINCIBLE_DURATION = 1500  # ms

PLAYER_HITBOX_OFFSET_X = 12
PLAYER_HITBOX_OFFSET_Y = 10
PLAYER_HITBOX_WIDTH = 40
PLAYER_HITBOX_HEIGHT = 37

SHOW_HITBOX = False


# =========================
# PLAYER BULLET SETTINGS
# =========================

PLAYER_BULLET_WIDTH = 16
PLAYER_BULLET_HEIGHT = 16
PLAYER_BULLET_SPEED = 9

# =========================
# PLAYER ENGINE OFFSET SETTINGS
# =========================

PLAYER_ENGINE_OFFSET_X = 0
PLAYER_ENGINE_OFFSET_Y = 0

PLAYER_POWERING_ENGINE_OFFSET_X = -1
PLAYER_POWERING_ENGINE_OFFSET_Y = -2


# =========================
# BULLET SPRITE SETTINGS
# =========================

PLAYER_BULLET_FRAME_WIDTH = 32
PLAYER_BULLET_FRAME_HEIGHT = 32
PLAYER_BULLET_DRAW_WIDTH = 36
PLAYER_BULLET_DRAW_HEIGHT = 36

SMALL_ENEMY_BULLET_FRAME_WIDTH = 16
SMALL_ENEMY_BULLET_FRAME_HEIGHT = 16
SMALL_ENEMY_BULLET_DRAW_WIDTH = 16
SMALL_ENEMY_BULLET_DRAW_HEIGHT = 16

BIG_ENEMY_BULLET_FRAME_WIDTH = 16
BIG_ENEMY_BULLET_FRAME_HEIGHT = 16
BIG_ENEMY_BULLET_DRAW_WIDTH = 24
BIG_ENEMY_BULLET_DRAW_HEIGHT = 24

BULLET_ANIMATION_SPEED_MS = 80

# =========================
# ADXL / MOVEMENT SETTINGS
# =========================

DEAD_ZONE = 15
SPEED_SCALE = 0.14


# =========================
# ENEMY SETTINGS
# =========================

ENEMY_WIDTH = 96
ENEMY_HEIGHT = 96
ENEMY_SPAWN_DELAY = 1200  # ms

MIN_ENEMY_SPAWN_DELAY = 350
MAX_ENEMY_SPEED = 8

# =========================
# ENEMY HITBOX SETTINGS
# =========================

ENEMY_HITBOX_OFFSET_X = 27
ENEMY_HITBOX_OFFSET_Y = 20
ENEMY_HITBOX_WIDTH = 40
ENEMY_HITBOX_HEIGHT = 42

BOSS_HITBOX_OFFSET_X = 35
BOSS_HITBOX_OFFSET_Y = 25
BOSS_HITBOX_WIDTH = 120
BOSS_HITBOX_HEIGHT = 90

# =========================
# ENEMY BULLET SETTINGS
# =========================

ENEMY_BULLET_WIDTH = 14
ENEMY_BULLET_HEIGHT = 14

BIG_ENEMY_BULLET_WIDTH = 20
BIG_ENEMY_BULLET_HEIGHT = 20

ENEMY_BULLET_SPEED = 5
MAX_ENEMY_BULLET_SPEED = 11
ENEMY_FIRE_DELAY = 1000  # ms

# =========================
# ENEMY ENGINE OFFSET SETTINGS
# =========================

SMALL_ENEMY_ENGINE_OFFSET_X = -1
SMALL_ENEMY_ENGINE_OFFSET_Y = -2

BIG_ENEMY_ENGINE_OFFSET_X = -1
BIG_ENEMY_ENGINE_OFFSET_Y = -2

# =========================
# MINI BOSS SETTINGS
# =========================

MINI_BOSS_SCORE = 250

MINI_BOSS_WIDTH = 190
MINI_BOSS_HEIGHT = 140
MINI_BOSS_HP = 30
MINI_BOSS_SPEED = 2


# =========================
# BOSS PHASE SETTINGS
# =========================

BOSS_PHASE_2_HP_RATIO = 0.5

BOSS_PHASE_1_SPEED = 2
BOSS_PHASE_2_SPEED = 4

BOSS_PHASE_1_FIRE_DELAY = 700
BOSS_PHASE_2_FIRE_DELAY = 420

BOSS_PHASE_2_SPREAD_SPEED = 3

BOSS_HP_BAR_COLOR = (230, 50, 50)
BOSS_PHASE_2_HP_BAR_COLOR = (255, 120, 40)

# =========================
# POWER-UP SETTINGS
# =========================

POWERUP_SIZE = 32
POWERUP_SPEED = 3
POWERUP_DROP_CHANCE = 0.25

RAPID_FIRE_DURATION = 6000      # ms
RAPID_FIRE_COOLDOWN = 150       # ms

TRIPLE_SHOT_DURATION = 6000
TRIPLE_SHOT_SIDE_SPEED = 3


# =========================
# EXPLOSION SETTINGS
# =========================

EXPLOSION_FRAME_TIME = 80  # ms

# =========================
# UI BAR SETTINGS
# =========================

POWERUP_BAR_FILL_OFFSET_X = 8
POWERUP_BAR_FILL_OFFSET_Y = 7
POWERUP_BAR_FILL_WIDTH = 166
POWERUP_BAR_FILL_HEIGHT = 4

BOSS_BAR_FILL_OFFSET_X = 8
BOSS_BAR_FILL_OFFSET_Y = 7
BOSS_BAR_FILL_WIDTH = 166
BOSS_BAR_FILL_HEIGHT = 4

POWERUP_RAPID_BAR_COLOR = (60, 180, 255)
POWERUP_TRIPLE_BAR_COLOR = (170, 90, 255)
BOSS_HP_BAR_COLOR = (230, 50, 50)

# =========================
# BACKGROUND SETTINGS
# =========================

BACKGROUND_SCROLL_SPEED = 0.8

# =========================
# AUDIO SETTINGS
# =========================

MUSIC_MAIN_MENU_VOLUME = 0.75
MUSIC_GAME_VOLUME = 0.35
MUSIC_BOSS_VOLUME = 0.50
MUSIC_VICTORY_VOLUME = 0.70
MUSIC_DEFEAT_VOLUME = 0.70

SFX_PLAYER_FIRE_VOLUME = 0.45
SFX_EXPLOSION_VOLUME = 0.60
SFX_POWERUP_VOLUME = 0.60
SFX_PLAYER_HIT_VOLUME = 0.65
SFX_BOSS_PHASE2_VOLUME = 0.75